### ISSUE TITLE
Agregar filtro de recibos no impresos fiscalmente.

### ISSUE THREAD

**Issue by ManfredoFerreras** [ManfredoFerreras/OpeAgencias#18]
Crear un filtro para listar las operaciones que no fueron impresas fiscalemente.

**Comment by ManfredoFerreras** [comment]
Actualizado

**Comment by HazielS** [comment]
yo lo estaba haciendo xd de ahora en adelante debemos asignarnoslo para que se sepa en cual estamos trabajando
