### ISSUE TITLE
Se repite el código de barras

### ISSUE THREAD

**Issue by HazielS** [ManfredoFerreras/OpeAgencias#6]
En la factura fiscal de varios paquetes, todos salen con el mismo código de barras.

**Comment by HazielS** [comment]
Resuelto en el último commit

**Comment by ManfredoFerreras** [comment]
Nítido.
Ya esta la facturación de envíos nacionales 1cn.

-----Mensaje original-----
De: "HazielS" <notifications@github.com>
Enviado el: ‎8/‎7/‎2015 12:16 PM
Para: "ManfredoFerreras/OpeAgencias" <OpeAgencias@noreply.github.com>
Asunto: Re: [OpeAgencias] Se repite el código de barras (#6)

Resuelto en el último commit
