### ISSUE TITLE
Validación de pasaporte

### ISSUE THREAD

**Issue by HazielS** [ManfredoFerreras/OpeAgencias#7]
Se debe validar que si el cliente es de tipo fiscal "Persona Física", puede, aunque no tenga cédula, facturar si tiene pasaporte.

**Comment by HazielS** [comment]
Hay que hacerlo en conjunto con la validación de si es Empresa o persona física; si es empresa necesita RNC, si es persona física, cédula o pasaporte.

**Comment by ManfredoFerreras** [comment]
Ya está.  El tema es en cadena.  Si tiene Cedula va con cedula, si no va
con rnc.  Estos tienen que ser solo números. si no, entoces va a Pasaporte.
que si permite caracteres.  Habria que ver si tiene algún patrón.

2015-08-06 11:54 GMT-04:00 HazielS <notifications@github.com>:

**Comment by ManfredoFerreras** [comment]
El cliente solo puede tener pasaporte si el tipo fiscal es persona fisica. Para los otros casos debe tener una cedula o un rnc válido.
